### ISSUE TITLE
Parameter for output file specification

### ISSUE THREAD

**Issue by karel-brinda** [cobilab/geco3#3]
Hello,

I really like GeCo3, but one limitation I'm currently facing is the lack of parameters for specifying the output: currently it's always `{input_fa}.co`.

Is there a chance that output file name could be specified via CLI?

Thanks

**Comment by pratas** [comment]
Hi Karel,

Thank you for your kind words.

This implementation is challenging because GeCo3 can compress multiple files simultaneously, for example: file1.txt:file2.txt:file3.txt (specified by the final argument). As a result, it automatically generates the corresponding output file(s). If GeCo3 processed only one file at a time, the implementation would be much simpler.
To achieve this, it would require uniform settings across all files and a reliable mechanism to verify the scheme’s correctness. Handling multiple files, however, is crucial for certain analysis tasks or for efficiently compressing several files while loading a reference only once.

Cheers
